name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
  issue_comment:
    types: [created]

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Determine Qodana Args'
        id: qodana_args
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          if [ "$GITHUB_EVENT_NAME" = "issue_comment" ] && echo "$COMMENT_BODY" | grep -q "@qodana_bot fix"; then
            echo "args=--apply-fixes" >> $GITHUB_OUTPUT
          else
            echo "args=" >> $GITHUB_OUTPUT
          fi

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' || (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@qodana_bot fix')) }}
        with:
          args: ${{ steps.qodana_args.outputs.args }}
          push-fixes: "branch"
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
